// lottery/src/components/Counter.tsx
import { createSignal } from 'solid-js';

/** */
export default function SolidCounter({ children }) {
  const [count, setCount] = createSignal(0);
  const add = () => setCount(count() + 1);
  const subtract = () => setCount(count() - 1);
 


  return (
    <>
      <div class="counter">
        <button onClick={subtract}>-</button>
        <pre>{count()}</pre>
        <button onClick={add}>+</button>
      </div>
      <div class="children">{children}</div>      
    </>
  );
}

// use-case/astro-vuejsfrankfurtmeetup-main/src/components/Counter.vue
<template>
   
  <div class="counter">
      <button @click="subtract()">-</button>
      <pre>{{ count }}</pre>
      <pre>{{ msg }}</pre>
      <button @click="add()">+</button>
  </div>

  <div class="children">
      <slot />
  </div>
</template>

<script>
import { ref } from 'vue';


export default {
  setup() {
    const count = ref(0)
    const msg="大鳥"
    const add = () => count.value = count.value + 1;
    const subtract = () => count.value = count.value - 1;
    return {
      count,
      add,
      subtract,
      msg
    }
  }
}
</script>
